server:
  port: 80
msyql:
  jdbcName: com.mysql.cj.jdbc.Driver
  dbUrl: jdbc:mysql://localhost:3306/demo_jpa01
  userName: root
  password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_jpa01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    

